/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mail_icon.glb -T 
Files: mail_icon.glb [53.73KB] > C:\Users\skidu\Desktop\TreyzeWebsite\public\models\mail_icon-transformed.glb [8.64KB] (84%)
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mail-icon-b9133b28050d43aeb973aa0f08f86441
Title: Mail Icon
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Mail(props) {
  const { nodes, materials } = useGLTF('/models/mail_icon-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Material.001']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials['Material.002']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/mail_icon-transformed.glb');
